src/Entity/Cart.php
<?php

namespace App\Entity;

use App\Repository\CartRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CartRepository::class)
 */
class Cart
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;



    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="carts")
     * @ORM\JoinColumn(nullable=false)
     */
    private $User;

    /**
     * @ORM\OneToMany(targetEntity=CartProduct::class, mappedBy="cart", orphanRemoval=true)
     */
    private $cartProducts;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $agreed;

    public function __construct()
    {
        $this->cartProducts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }


    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }

    /**
     * @return Collection|CartProduct[]
     */
    public function getCartProducts(): Collection
    {
        return $this->cartProducts;
    }

    public function addCartProduct(CartProduct $cartProduct): self
    {
        if (!$this->cartProducts->contains($cartProduct)) {
            $this->cartProducts[] = $cartProduct;
            $cartProduct->setCart($this);
        }

        return $this;
    }

    public function removeCartProduct(CartProduct $cartProduct): self
    {
        if ($this->cartProducts->removeElement($cartProduct)) {
            // set the owning side to null (unless already changed)
            if ($cartProduct->getCart() === $this) {
                $cartProduct->setCart(null);
            }
        }

        return $this;
    }

    public function getAgreed(): ?bool
    {
        return $this->agreed;
    }

    public function setAgreed(?bool $agreed): self
    {
        $this->agreed = $agreed;

        return $this;
    }
}

src/Entity/Region.php
<?php

namespace App\Entity;

use App\Repository\RegionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=RegionRepository::class)
 */
class Region
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $country;

    /**
     * @ORM\OneToMany(targetEntity=Product::class, mappedBy="region")
     */
    private $products;

    public function __construct()
    {
        $this->products = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }

    /**
     * @return Collection|Product[]
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(Product $product): self
    {
        if (!$this->products->contains($product)) {
            $this->products[] = $product;
            $product->setRegion($this);
        }

        return $this;
    }

    public function removeProduct(Product $product): self
    {
        if ($this->products->removeElement($product)) {
            // set the owning side to null (unless already changed)
            if ($product->getRegion() === $this) {
                $product->setRegion(null);
            }
        }

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\Email(
     *      message = "votre email '{{ value }}' n\'est pas un email valide."
     * )
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;


    /**
     * @return mixed
     */
    public function getLastCart()
    {
        return $this->carts->last();
    }


    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(
     *     message="Ne peut pas être vide"
     * )
     * @Assert\Length(
     *      min = 4,
     *      max = 20,
     *      minMessage = "Votre nom d\'utilisateur doit contenir au minimum {{ limit }} caractères",
     *      maxMessage = "Votre nom d\'utilisateur doit contenir au maximum {{ limit }} caractères"
     * )
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(
     *     message="Ne peut pas être vide"
     * )
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(
     *     message="Ne peut pas être vide"
     * )
     */
    private $lastname;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="user")
     */
    private $comments;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    /**
     * @ORM\OneToMany(targetEntity=Cart::class, mappedBy="User", orphanRemoval=true)
     */
    private $carts;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->carts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setUser($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getUser() === $this) {
                $comment->setUser(null);
            }
        }

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    /**
     * @return Collection|Cart[]
     */
    public function getCarts(): Collection
    {
        return $this->carts;
    }

    public function addCart(Cart $cart): self
    {
        if (!$this->carts->contains($cart)) {
            $this->carts[] = $cart;
            $cart->setUser($this);
        }

        return $this;
    }

    public function removeCart(Cart $cart): self
    {
        if ($this->carts->removeElement($cart)) {
            // set the owning side to null (unless already changed)
            if ($cart->getUser() === $this) {
                $cart->setUser(null);
            }
        }

        return $this;
    }
}

src/Form/RegionType.php
<?php

namespace App\Form;

use App\Entity\Region;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RegionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('country')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Region::class,
        ]);
    }
}

src/Controller/RegionController.php
<?php

namespace App\Controller;

use App\Entity\Region;
use App\Form\RegionType;
use App\Repository\CategoryRepository;
use App\Repository\RegionRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/region")
 */
class RegionController extends AbstractController
{
    /**
     * @Route("/", name="region_index", methods={"GET"})
     * @param RegionRepository $regionRepository
     * @return Response
     */
    public function index(RegionRepository $regionRepository, CategoryRepository $categoryRepository): Response
    {
        return $this->render('region/index.html.twig', [
            'regions' => $regionRepository->findAll(),
            'categories' => $categoryRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="region_new", methods={"GET","POST"})
     * @param Request $request
     * @IsGranted ("ROLE_ADMIN")
     * @return Response
     */
    public function new(Request $request, RegionRepository $regionRepository, CategoryRepository $categoryRepository): Response
    {
        $region = new Region();
        $form = $this->createForm(RegionType::class, $region);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($region);
            $entityManager->flush();

            return $this->redirectToRoute('region_index');
        }

        return $this->render('region/new.html.twig', [
            'region' => $region,
            'form' => $form->createView(),
            'regions' => $regionRepository->findAll(),
            'categories' => $categoryRepository->findAll(),
        ]);
    }

    /**
     * @Route("/{id}", name="region_show", methods={"GET"})
     * @param Region $region
     * @return Response
     */
    public function show(Region $region, RegionRepository $regionRepository, CategoryRepository $categoryRepository): Response
    {
        return $this->render('region/show.html.twig', [
            'region' => $region,
            'regions' => $regionRepository->findAll(),
            'categories' => $categoryRepository->findAll(),
        ]);
    }

    /**
     * @Route("/{id}/edit", name="region_edit", methods={"GET","POST"})
     * @param Request $request
     * @param Region $region
     * @IsGranted ("ROLE_ADMIN")
     * @return Response
     */
    public function edit(Request $request, Region $region, RegionRepository $regionRepository, CategoryRepository $categoryRepository): Response
    {
        $form = $this->createForm(RegionType::class, $region);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('region_index');
        }

        return $this->render('region/edit.html.twig', [
            'region' => $region,
            'form' => $form->createView(),
            'regions' => $regionRepository->findAll(),
            'categories' => $categoryRepository->findAll(),
        ]);
    }

    /**
     * @Route("/{id}/delete", name="region_delete", methods={"DELETE"})
     * @param Request $request
     * @param Region $region
     * @return Response
     * @IsGranted ("ROLE_SUPER")
     *
     */
    public function delete(Request $request, Region $region): Response
    {
        if ($this->isCsrfTokenValid('delete'.$region->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($region);
            $entityManager->flush();
        }

        return $this->redirectToRoute('region_index');
    }
}

templates/region/_delete_form.html.twig
<form method="post" action="{{ path('region_delete', {'id': region.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ region.id) }}">
    <button class="btn btn-danger mt-2">Delete Region</button>
</form>

templates/region/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/region/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Region{% endblock %}

{% block body %}
<div class="container rounded mt-3 p-2" style="width: 600px; background: #fcf9f3">
    <div class="d-flex justify-content-center ">
        <h1 class="text-danger">Edit Region</h1>
    </div>
<div class="container-fluid" style="width: 500px;">
    {{ include('region/_form.html.twig', {'button_label': 'Update'}) }}

    <a class="btn btn-primary mt-2" href="{{ path('region_index') }}">back to list</a>

    {{ include('region/_delete_form.html.twig') }}
</div>
{% endblock %}

templates/region/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Region index{% endblock %}

{% block body %}
    <h1>Region index</h1>

    <table class="table">
        <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Country</th>
            <th>actions</th>
        </tr>
        </thead>
        <tbody>
        {% for region in regions %}
            <tr>
                <td>{{ region.id }}</td>
                <td>{{ region.name }}</td>
                <td>{{ region.country }}</td>
                <td>
                    <a href="{{ path('region_show', {'id': region.id}) }}">show</a>
                    <a href="{{ path('region_edit', {'id': region.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('region_new') }}">Create new</a>
{% endblock %}

templates/region/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Region{% endblock %}

{% block body %}
<div class="container rounded mt-3 p-2" style="width: 600px; background: #fcf9f3">
    <div class="d-flex justify-content-center">
        <h1 class="text-danger">Create new Region</h1>
    </div>
    {{ include('region/_form.html.twig') }}

    <a class="btn btn-primary mt-3" href="{{ path('region_index') }}">Back to list</a>
</div>
{% endblock %}

templates/region/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ region.country }} - {{ region.name }}{% endblock %}

{% block body %}

<div class="d-flex justify-content-center mt-4 mb-4">
    <h1 style="color: #a71d2a">{{ region.country }} - {{ region.name }}</h1>
</div>
{% if is_granted('ROLE_SUPER') %}
    <div class="d-flex justify-content-center">
        <a href="{{ path('region_new')}}" class="btn btn-success mr-2">Add a New Region</a>

        <a href="{{ path('region_edit', {'id': region.id}) }}" class="btn btn-warning mr-2">Edit Region</a>

        <a href="{{ path('region_delete', {'id': region.id}) }}" class="btn btn-danger">Delete Region</a>
    </div>
{% endif %}
<div class="d-flex mt-3 ml-5">
    <div class="card-columns ">
    {% for product in region.products %}
        <div class="card align-items-center h-100" style="width: 30rem; height: 35rem; border-color: #bf9b30; background: #fcf9f3">
            <div class="card-body">
                <h4 class="card-header text-center">
                    <a style="color: #a71d2a; text-decoration: none" href="{{ path('product_show', {'id': product.id}) }}">{{ product.name }}</a>
                </h4>
                <div class="d-flex justify-content-between align-items-center">
                    <ul class="list-group list-group-flush text-left">
                        <li class="list-group-item" style="background: #fcf9f3">HTVA : {{ product.priceHTVA }} €</li>
                        <li class="list-group-item" style="background: #fcf9f3">TVAC ({{ product.tva *100 }}%)
                            : {{ product.priceHTVA + (product.priceHTVA * product.tva) }} €
                        </li>
                        <li class="list-group-item" style="background: #fcf9f3">Domain : {{ product.domain }}</li>
                        <li class="list-group-item" style="background: #fcf9f3">Country : {{ product.region.country }}</li>
                        <li class="list-group-item" style="background: #fcf9f3">Region : <a
                                    href="{{ path('region_show', {'id': product.region.id}) }}">{{ product.region.name }}</a>
                        </li>
                        <li class="list-group-item" style="background: #fcf9f3">Quantity left : {{ product.quantity }}</li>
                    </ul>
                    <img class="card-img-top miniature mt-2 mb-2" src="{{ asset("images/products/"~product.image) }}"
                         alt="{{ product.name }}"/>
                </div>
                <div class="card-footer text-center">
                    {% if app.user is not null %}
                        <a href="{{ path('add_to_cart', {'id' : app.user.lastCart.id, 'product' : product.id}) }}"
                           class="btn btn-primary"><i class="bi bi-cart-plus-fill"></i></a>
                    {% else %}
                        <a href="{{ path('app_login') }}" class="btn btn-dark"><i class="bi bi-cart-plus-fill"></i></a>
                    {% endif %}
                    {% if is_granted('ROLE_ADMIN') %}
                        <a href="{{ path('product_edit', {'id': product.id}) }}" class="btn btn-warning"><i class="bi bi-pencil-square"></i></a>
                    {% endif %}
                    {% if is_granted('ROLE_SUPER') %}
                        <a href="{{ path('product_delete', {'id': product.id}) }}" class="btn btn-danger"><i class="bi bi-trash"></i></a>
                    {% endif %}
                </div>
            </div>
        </div>

    {% else %}
        <tr>
            <td colspan="7">no records found</td>
        </tr>
    {% endfor %}

    </div>
</div>
{% endblock %}